version: '3'

services:
    mongo:
        deploy:
            resources:
                limits:
                    cpus: 0.50
                    memory: 512M
                reservations:
                    cpus: 0.25
                    memory: 128M
        image: mongo
        container_name: mongo
        restart: always
        hostname: mongo
        ports:
            - 27017:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: jonas
            MONGO_INITDB_ROOT_PASSWORD: jonas123
        volumes:
            - mongo_volume:/data/db
            - mongo_volume:/data/configdb
        networks:
            - mongo_network
networks:
    mongo_network:
        driver: bridge
volumes:
    mongo_volume: